/*
 * ConsultaFactNDNC_CXP.java
 *
 * Created on 22/06/2011, 04:00:00 PM
 */

package interfase.consultas;

import Mail.Bitacora;
import accesoDatos.CMD;
import accesoDatos.UtilBD;
import interfase.transacciones.AnulacionFacturasCXP;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.utilitarios.Ut;

/**
 *
 * @author Bosco Garita
 */
@SuppressWarnings("serial")
public class ConsultaFactNDNC_CXP extends JFrame {

    private ResultSet  rs;
    private Connection sConn = null; // Shared connection
    private String tipoDoc = "1";   // Tipo de documento (1=Fact,2=NC,3=ND)
    
    /** Creates new form
     * @param c
     * @throws java.sql.SQLException 
     */
    public ConsultaFactNDNC_CXP(Connection c) throws SQLException {
        initComponents();

        sConn = c;
        
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                btnSalirActionPerformed(null);
            } // end windowClosing
        } // end class
        ); // end Listener
    } // end constructor
    
    // Segundo constructor
    public ConsultaFactNDNC_CXP(Connection c, String doc, String tipoDoc) throws SQLException {
        initComponents();
        this.tipoDoc = tipoDoc;
        this.txtFacnume.setText(doc);
        switch (tipoDoc){
            case "1": this.radFactura.setSelected(true); break;
            case "2": this.radNC.setSelected(true); break;
            case "3": this.radND.setSelected(true); break;
        } // end switch
        sConn = c;
        
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                btnSalirActionPerformed(null);
            } // end windowClosing
        } // end class
        ); // end Listener
        
        this.txtFacnumeActionPerformed(null);
    } // end constructor
    
    

    public void setConexion(Connection c){ sConn = c; }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radFactura = new javax.swing.JRadioButton();
        radNC = new javax.swing.JRadioButton();
        radND = new javax.swing.JRadioButton();
        txtFacnume = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtClidesc = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        lblFacfech = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMoneda = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIV = new javax.swing.JFormattedTextField();
        txtFacdesc = new javax.swing.JFormattedTextField();
        txtFacmont = new javax.swing.JFormattedTextField();
        txtFacsald = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        lblRefInv = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaObservaciones = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabDetalle = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuAnular = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consultar facturas, ND y NC (CXP)");

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 0))); // NOI18N

        buttonGroup1.add(radFactura);
        radFactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radFactura.setSelected(true);
        radFactura.setText("Factura");
        radFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radFacturaMouseClicked(evt);
            }
        });

        buttonGroup1.add(radNC);
        radNC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radNC.setText("Nota de crédito");
        radNC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radNCMouseClicked(evt);
            }
        });

        buttonGroup1.add(radND);
        radND.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radND.setText("Nota de débito");
        radND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radNDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radFactura)
                    .addComponent(radNC)
                    .addComponent(radND)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radFactura, radNC, radND});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radNC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radND))
        );

        txtFacnume.setColumns(6);
        txtFacnume.setForeground(new java.awt.Color(255, 0, 51));
        txtFacnume.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFacnume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFacnumeFocusGained(evt);
            }
        });
        txtFacnume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacnumeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Fecha");

        txtClidesc.setEditable(false);
        txtClidesc.setColumns(25);
        txtClidesc.setForeground(new java.awt.Color(255, 102, 102));
        txtClidesc.setToolTipText("");
        txtClidesc.setFocusable(false);
        txtClidesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Proveedor");

        lblFacfech.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFacfech.setForeground(java.awt.Color.blue);
        lblFacfech.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Usuario");

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUser.setForeground(java.awt.Color.blue);
        lblUser.setText(" ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tipo");

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTipo.setForeground(java.awt.Color.blue);
        lblTipo.setText(" ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Moneda");

        lblMoneda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMoneda.setForeground(java.awt.Color.magenta);
        lblMoneda.setText(" ");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Impuesto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Descuento");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Monto");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Saldo");

        txtIV.setEditable(false);
        txtIV.setBackground(new java.awt.Color(255, 255, 153));
        txtIV.setForeground(java.awt.Color.blue);
        txtIV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtIV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIV.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtFacdesc.setEditable(false);
        txtFacdesc.setBackground(new java.awt.Color(255, 255, 153));
        txtFacdesc.setForeground(java.awt.Color.blue);
        txtFacdesc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtFacdesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFacdesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtFacmont.setEditable(false);
        txtFacmont.setBackground(new java.awt.Color(255, 255, 153));
        txtFacmont.setForeground(java.awt.Color.blue);
        txtFacmont.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtFacmont.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFacmont.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        txtFacsald.setEditable(false);
        txtFacsald.setBackground(new java.awt.Color(255, 255, 153));
        txtFacsald.setForeground(java.awt.Color.blue);
        txtFacsald.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtFacsald.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFacsald.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIV, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtFacdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtFacmont, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txtFacsald, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtIV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtFacdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFacmont, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFacsald, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Ref. Inv");

        lblRefInv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRefInv.setForeground(java.awt.Color.blue);
        lblRefInv.setText(" ");

        txaObservaciones.setEditable(false);
        txaObservaciones.setColumns(20);
        txaObservaciones.setLineWrap(true);
        txaObservaciones.setRows(5);
        txaObservaciones.setWrapStyleWord(true);
        txaObservaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Observaciones"));
        txaObservaciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txaObservacionesFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txaObservaciones);

        tabDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Bodega", "Descripción", "Cantidad", "Costo", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabDetalle.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tabDetalle);
        tabDetalle.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tabDetalle.getColumnModel().getColumnCount() > 0) {
            tabDetalle.getColumnModel().getColumn(0).setMinWidth(70);
            tabDetalle.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabDetalle.getColumnModel().getColumn(0).setMaxWidth(150);
            tabDetalle.getColumnModel().getColumn(1).setMinWidth(30);
            tabDetalle.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabDetalle.getColumnModel().getColumn(1).setMaxWidth(70);
            tabDetalle.getColumnModel().getColumn(2).setMinWidth(100);
            tabDetalle.getColumnModel().getColumn(2).setPreferredWidth(250);
            tabDetalle.getColumnModel().getColumn(2).setMaxWidth(300);
            tabDetalle.getColumnModel().getColumn(3).setMinWidth(50);
            tabDetalle.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabDetalle.getColumnModel().getColumn(3).setMaxWidth(100);
            tabDetalle.getColumnModel().getColumn(4).setMinWidth(50);
            tabDetalle.getColumnModel().getColumn(4).setPreferredWidth(90);
            tabDetalle.getColumnModel().getColumn(4).setMaxWidth(150);
            tabDetalle.getColumnModel().getColumn(5).setMinWidth(50);
            tabDetalle.getColumnModel().getColumn(5).setPreferredWidth(90);
            tabDetalle.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        mnuArchivo.setText("Archivo");

        mnuAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelar16.png"))); // NOI18N
        mnuAnular.setText("Anular");
        mnuAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAnularActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuAnular);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtFacnume, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClidesc, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRefInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFacfech, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtClidesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFacnume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblRefInv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblMoneda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblFacfech))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        btnSalirActionPerformed(null);
}//GEN-LAST:event_mnuSalirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtFacnumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacnumeActionPerformed
        Bitacora b = new Bitacora();
        String sqlSent = 
                "Select " +
                "	a.factura," +
                "	a.tipo as tipodoc," +
                "	a.procode," +
                "	b.prodesc," +
                "	dtoc(a.fecha_fac) as fecha," +
                "	if(a.vence_en > 0, 'Crédito','Contado') as tipo," +
                "	a.total_fac * a.tipoca as monto," +
                "	a.descuento * a.tipoca as descuento," +
                "	a.impuesto * a.tipoca  as impuesto," +
                "       a.saldo * a.tipoca as saldo, " +
                "	a.refinv," +
                "       a.user,  " +
                "       a.observaciones ," +
                "	Concat(c.simbolo, ' ', c.descrip) as moneda," +
                "	a.saldo * a.tipoca " +
                "From cxpfacturas a, inproved b, monedas c " +
                "Where a.factura = ? and tipo = ? " +
                "and a.procode = b.procode and a.codigoTC = c.codigo";
        
        String factura, tipo;
        PreparedStatement ps;
        short movtido;
        factura = txtFacnume.getText();
        
        tipo = "FAC";
        movtido = 2;
        
        if (this.radNC.isSelected()){
            tipo = "NCR";
            //movtido = 7; Este tipo aún no se ha definido Bosco 11/10/2015
        } else if (this.radND.isSelected()){
            tipo = "NDB";
            movtido = 7;
        } // end if
        
        try {
            
            ps = sConn.prepareStatement(
                    sqlSent, 
                    ResultSet.TYPE_SCROLL_SENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            
            ps.setString(1, factura);
            ps.setString(2, tipo);
            rs = CMD.select(ps);
            if (rs == null || !rs.first()) {
                JOptionPane.showMessageDialog(null, 
                        "Documento no encontrado",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } // end if

            // Cargar el encabezado de la factura
            txtClidesc.setText(rs.getString("prodesc"));
            lblFacfech.setText(rs.getString("fecha"));
            lblUser.setText(rs.getString("user"));
            lblTipo.setText(rs.getString("tipo"));
            lblMoneda.setText(rs.getString("moneda"));
            lblRefInv.setText(rs.getString("refinv"));
            txaObservaciones.setText(rs.getString("observaciones"));

            // Cargar los totales de la factura (ND-NC) con formato
            this.txtIV.setText(
                    Ut.setDecimalFormat(rs.getString("impuesto"),"#,##0.00"));
            this.txtFacdesc.setText(
                    Ut.setDecimalFormat(rs.getString("descuento"),"#,##0.00"));
            this.txtFacmont.setText(
                    Ut.setDecimalFormat(rs.getString("monto"),"#,##0.00"));
            this.txtFacsald.setText(
                    Ut.setDecimalFormat(rs.getString("saldo"),"#,##0.00"));

            ps.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            b.setLogLevel(Bitacora.ERROR);
            b.writeToLog(this.getClass().getName() + "--> " + ex.getMessage(), Bitacora.ERROR);
            return;
        } // end try-catch
        
        // Bosco agregado 18/12/2016
        // Limpio la tabla antes de poner los nuevos datos
        Ut.clearJTable(tabDetalle);
        
        // Bosco agregado 18/10/2014
        // Si la factura tiene referencia en inventarios cargo el detalle
        sqlSent = 
                "Select " +
                "	b.artcode," +
                "	b.bodega, " +
                "	c.artdesc," +
                "	b.movcant," +
                "	b.movcoun * d.tipoca as movcoun," +
                "	b.movcant *	b.movcoun * d.tipoca as total   " +
                "from cxpfacturas a, inmovimd b, inarticu c, inmovime d " +
                "Where a.factura = ? and a.tipo = ? " +
                "and a.refinv > '' " + // Bosco agregado 18/12/2016
                "and a.refinv = b.movdocu and b.movtido = ? " +
                "and b.movdocu = d.movdocu and b.movtido = d.movtido " +
                "and b.artcode = c.artcode";
        
        try {
            
            ps = sConn.prepareStatement(
                    sqlSent, 
                    ResultSet.TYPE_SCROLL_SENSITIVE, 
                    ResultSet.CONCUR_READ_ONLY);
            
            ps.setString(1, factura);
            ps.setString(2, tipo);
            ps.setShort(3, movtido);
            rs = CMD.select(ps);
            if (rs == null || !rs.first()) {
                ps.close();
                return;
            } // end if

            // Establezco el número de filas adecuado para la consulta
            rs.last();
            int dataRows = rs.getRow();
            DefaultTableModel dtm = (DefaultTableModel) tabDetalle.getModel();
            int tableRows = dtm.getRowCount();
            if(tableRows < dataRows){
                dtm.setRowCount(dataRows);
                tabDetalle.setModel(dtm);
                tableRows = dataRows;
            } // end if

            int r;
            
            // Cargar el detalle de la factura en inventarios
            rs.beforeFirst();
            r = 0;
            while (rs.next() && r < tableRows){
                this.tabDetalle.setValueAt(rs.getString("artcode"), r, 0);
                this.tabDetalle.setValueAt(rs.getString("bodega" ), r, 1);
                this.tabDetalle.setValueAt(rs.getString("artdesc"), r, 2);
                this.tabDetalle.setValueAt(rs.getDouble("movcant"), r, 3);
                this.tabDetalle.setValueAt(rs.getDouble("movcoun"), r, 4);
                this.tabDetalle.setValueAt(rs.getDouble("total"), r, 5);
                r++;
            } // end while

            ps.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            b.setLogLevel(Bitacora.ERROR);
            b.writeToLog(this.getClass().getName() + "--> " + ex.getMessage(), Bitacora.ERROR);
        } // end try-catch
}//GEN-LAST:event_txtFacnumeActionPerformed

    private void txtFacnumeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFacnumeFocusGained
        txtFacnume.selectAll();
}//GEN-LAST:event_txtFacnumeFocusGained

    private void radFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radFacturaMouseClicked
        if (radFactura.isSelected()) {
            tipoDoc = "1";
        } // end if
        txtFacnume.requestFocusInWindow();
    }//GEN-LAST:event_radFacturaMouseClicked

    private void radNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radNDMouseClicked
        if (radND.isSelected()) {
            tipoDoc = "3";
        } // end if
        txtFacnume.requestFocusInWindow();
    }//GEN-LAST:event_radNDMouseClicked

    private void radNCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radNCMouseClicked
        if (radNC.isSelected()) {
            tipoDoc = "2";
        } // end if
        txtFacnume.requestFocusInWindow();
    }//GEN-LAST:event_radNCMouseClicked

    private void mnuAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAnularActionPerformed
        new AnulacionFacturasCXP(
                new java.awt.Frame(),
                true,       // Modal
                sConn,      // Conexión
                txtFacnume.getText().trim())        // Número de documento
                .setVisible(true);
    }//GEN-LAST:event_mnuAnularActionPerformed

    private void txaObservacionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txaObservacionesFocusLost
        if (txaObservaciones.getText().trim().length() > 150){
            JOptionPane.showMessageDialog(null,
                "El máximo permitido de caracteres para el campo\n" +
                "observaciones es de 150.\n\n" +
                "Corríjalo antes de continuar.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } // end if
    }//GEN-LAST:event_txaObservacionesFocusLost


    /**
     * @param c
    */
    public static void main(final Connection c) {
        
        try {
            if (!UtilBD.tienePermiso(c,"ConsultaFactNDNC_CXP")){
                JOptionPane.showMessageDialog(null,
                        "Usted no está autorizado para ejecutar este proceso",
                        "Error - Permisos",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } // end if
            //DataBaseConnection.setFreeConnection("temp");
        } catch (Exception ex) {
            Logger.getLogger(ConsultaFactNDNC_CXP.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            ConsultaFactNDNC_CXP run = new ConsultaFactNDNC_CXP(c);
            run.setVisible(true);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, 
                     ex.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        } // end try-catch
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFacfech;
    private javax.swing.JLabel lblMoneda;
    private javax.swing.JLabel lblRefInv;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem mnuAnular;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JRadioButton radFactura;
    private javax.swing.JRadioButton radNC;
    private javax.swing.JRadioButton radND;
    private javax.swing.JTable tabDetalle;
    private javax.swing.JTextArea txaObservaciones;
    private javax.swing.JFormattedTextField txtClidesc;
    private javax.swing.JFormattedTextField txtFacdesc;
    private javax.swing.JFormattedTextField txtFacmont;
    private javax.swing.JFormattedTextField txtFacnume;
    private javax.swing.JFormattedTextField txtFacsald;
    private javax.swing.JFormattedTextField txtIV;
    // End of variables declaration//GEN-END:variables

} // end class
