/*
 * ConsultaFacturacionTransito.java
 *
 * Created on 27/01/2011, 09:51:41 PM by Bosco Garita
 * Desplegar los pedidos enviados a F8 (tránsito)
 * 
 */

package interfase.consultas;

import accesoDatos.UtilBD;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import logica.utilitarios.FormatoTabla;

/**
 *
 * @author Bosco Garita
 */
@SuppressWarnings("serial")
public class ConsultaFacturacionTransito extends javax.swing.JFrame {
    Connection conn = null;
    private ResultSet rs = null;

    /** Creates new form JFrame1
     * @param c
     * @throws java.sql.SQLException */
    public ConsultaFacturacionTransito(Connection c)
            throws SQLException {
        initComponents();
        
        conn = c;

        // Formateo la tabla
        FormatoTabla formato = new FormatoTabla();
        formato.setStringColor(Color.magenta);
        formato.setStringHorizontalAlignment(SwingConstants.LEFT);
        formato.getTableCellRendererComponent(tblDetalle,
                tblDetalle.getValueAt(0, 3),
                tblDetalle.isCellSelected(0, 3),
                tblDetalle.isFocusOwner(), 0, 3);

        this.tblDetalle.setDefaultRenderer(String.class, formato);

        String sqlSelect = 
                "Select          " +
                "    c.clidesc,  " +
                "    b.artdesc,  " +
                "    a.bodega,   " +
                "    a.reservado " +
                "from pedidofd a, inarticu b, inclient c " +
                "Where a.facnume = c.clicode " +
                "and a.artcode = b.artcode   ";

        PreparedStatement ps = conn.prepareStatement(sqlSelect);
        rs = ps.executeQuery();
        if (!rs.first()){
            return;
        } // end if

        // Obtengo el número de filas obtenidas en ResultSet
        rs.last();
        int totalFilas = rs.getRow();
        
        // Obtener el modelo de la tabla y establecer el número exacto
        // de filas.
        DefaultTableModel dtm = (DefaultTableModel) tblDetalle.getModel();
        dtm.setRowCount(totalFilas);
        tblDetalle.setModel(dtm);

        rs.beforeFirst();
        int row = 0;
        // Cargar los datos en la tabla
        while (rs.next()){
            tblDetalle.setValueAt(rs.getString("clidesc"), row, 0);
            tblDetalle.setValueAt(rs.getString("artdesc"), row, 1);
            tblDetalle.setValueAt(rs.getString("bodega"), row, 2);
            tblDetalle.setValueAt(rs.getDouble("reservado"), row, 3);
            row++;
        } // end while
        rs.close();

    } // end constructor
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación en tránsito");
        setLocationByPlatform(true);

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Artículo", "Bodega", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalle.setToolTipText("Montos expresados en moneda local");
        tblDetalle.setColumnSelectionAllowed(true);
        tblDetalle.setGridColor(new java.awt.Color(0, 102, 255));
        jScrollPane2.setViewportView(tblDetalle);
        tblDetalle.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDetalle.getColumnModel().getColumn(0).setMinWidth(100);
        tblDetalle.getColumnModel().getColumn(0).setPreferredWidth(180);
        tblDetalle.getColumnModel().getColumn(0).setMaxWidth(300);
        tblDetalle.getColumnModel().getColumn(1).setMinWidth(100);
        tblDetalle.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblDetalle.getColumnModel().getColumn(1).setMaxWidth(300);
        tblDetalle.getColumnModel().getColumn(2).setMinWidth(35);
        tblDetalle.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblDetalle.getColumnModel().getColumn(2).setMaxWidth(70);
        tblDetalle.getColumnModel().getColumn(3).setMinWidth(40);
        tblDetalle.getColumnModel().getColumn(3).setPreferredWidth(60);
        tblDetalle.getColumnModel().getColumn(3).setMaxWidth(75);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addGap(4, 4, 4))
        );

        setSize(new java.awt.Dimension(710, 253));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
}//GEN-LAST:event_mnuSalirActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    /**
     * @param c
    */
    public static void main(Connection c) {
        try {
            if (!UtilBD.tienePermiso(c,"FacturacionTransito")){
                JOptionPane.showMessageDialog(null,
                        "Usted no está autorizado para ejecutar este proceso",
                        "Error - Permisos",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } // end if
        } catch (Exception ex) {
            Logger.getLogger(ConsultaFacturacionTransito.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            ConsultaFacturacionTransito run = new ConsultaFacturacionTransito(c);
            run.setVisible(true);            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTable tblDetalle;
    // End of variables declaration//GEN-END:variables
   
} // end class