/*
 * RepExistenciasPB.java
 *
 * Created on 02/09/2009, 08:50:28 PM
 */

package interfase.reportes;

import accesoDatos.UtilBD;
import interfase.otros.Buscador;
import interfase.otros.Navegador;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Exceptions.NotUniqueValueException;
import Mail.Bitacora;
import logica.utilitarios.SQLInjectionException;
import logica.utilitarios.Ut;

/**
 *
 * @author Bosco Garita
 */
@SuppressWarnings("serial")
public class RepExistenciasPB extends JFrame {
    private Connection conn = null;
    Navegador Nav = null;
    private Buscador   bd = null;
    // Constantes para las búsquedas
    private final int ARTCODE1 = 1;
    private final int ARTCODE2 = 2;
    private final int BODEGA1  = 3;
    private final int BODEGA2  = 4;

    private int objetoBusqueda = ARTCODE1;
    
    /** Creates new form */
    public RepExistenciasPB(Connection c) throws SQLException {
        initComponents();

        conn = c;
        
        spnArtprec.setVisible(false);
        cboCosto.setVisible(false);
        jLabel3.setVisible(false);

        Nav = new Navegador();
        Nav.setConexion(conn);
    } // end constructor

    public void setConexion(Connection c){ conn = c; }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblArtcode = new javax.swing.JLabel();
        lblArtcode4 = new javax.swing.JLabel();
        txtArtcode1 = new javax.swing.JFormattedTextField();
        txtBodega1 = new javax.swing.JFormattedTextField();
        lblArtcode2 = new javax.swing.JLabel();
        lblArtcode3 = new javax.swing.JLabel();
        txtArtcode2 = new javax.swing.JFormattedTextField();
        txtBodega2 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        radExcluirSE = new javax.swing.JRadioButton();
        radExcluirCE = new javax.swing.JRadioButton();
        radExcluirNinguno = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboOrden = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboTipoRep = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboCosto = new javax.swing.JComboBox();
        spnArtprec = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        txtMargen = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmdImprimir = new javax.swing.JButton();
        cmdCerrar = new javax.swing.JButton();
        chkSoloOferta = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuEdicion = new javax.swing.JMenu();
        mnuBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Existencias por bodega");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rangos del reporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 0))); // NOI18N

        lblArtcode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode.setForeground(new java.awt.Color(0, 51, 255));
        lblArtcode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode.setText("Artículos");
        lblArtcode.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblArtcode4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode4.setForeground(new java.awt.Color(0, 51, 255));
        lblArtcode4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode4.setText("Bodegas");
        lblArtcode4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            txtArtcode1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("********************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtArtcode1.setToolTipText("Código del artículo - Blanco = todos");
        txtArtcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtcode1ActionPerformed(evt);
            }
        });
        txtArtcode1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtcode1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtcode1FocusLost(evt);
            }
        });

        try {
            txtBodega1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBodega1.setToolTipText("Código de bodega - Blanco = todas");
        txtBodega1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBodega1ActionPerformed(evt);
            }
        });
        txtBodega1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBodega1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBodega1FocusLost(evt);
            }
        });

        lblArtcode2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode2.setForeground(new java.awt.Color(255, 0, 204));
        lblArtcode2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode2.setText("Desde");
        lblArtcode2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblArtcode3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode3.setForeground(new java.awt.Color(255, 0, 204));
        lblArtcode3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode3.setText("Hasta");
        lblArtcode3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            txtArtcode2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("********************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtArtcode2.setToolTipText("Código del artículo - Blanco = todos");
        txtArtcode2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtcode2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtcode2FocusLost(evt);
            }
        });

        try {
            txtBodega2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBodega2.setToolTipText("Código de bodega - Blanco = todas");
        txtBodega2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBodega2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBodega2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtcode)
                    .addComponent(txtArtcode1)
                    .addComponent(txtArtcode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtcode4)
                    .addComponent(txtBodega1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(txtBodega2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtArtcode1, txtArtcode2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBodega1, txtBodega2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblArtcode4)
                    .addComponent(lblArtcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblArtcode2)
                    .addComponent(txtArtcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBodega1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblArtcode3)
                    .addComponent(txtArtcode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBodega2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir artículos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 0))); // NOI18N

        buttonGroup1.add(radExcluirSE);
        radExcluirSE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radExcluirSE.setSelected(true);
        radExcluirSE.setText("Sin existencia");
        radExcluirSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(radExcluirCE);
        radExcluirCE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radExcluirCE.setText("Con existencia");

        buttonGroup1.add(radExcluirNinguno);
        radExcluirNinguno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radExcluirNinguno.setText("Ninguno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radExcluirSE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(radExcluirCE, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radExcluirNinguno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(radExcluirSE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(radExcluirCE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(radExcluirNinguno)
                .addGap(6, 6, 6))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ordenar reporte por");

        cboOrden.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Descripción", "Familia" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tipo de reporte");

        cboTipoRep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Máximos y mínimos", "Costos FOB y promedio", "Fecha último movimiento", "Precio de lista", "Precios y utilidades" }));
        cboTipoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoRepActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cálculo del costo");

        cboCosto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Costo total", "Costo unitario" }));

        spnArtprec.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboOrden, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cboCosto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTipoRep, 0, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnArtprec, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnArtprec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(cboCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Margen a incluir:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        try {
            txtMargen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##%")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMargen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMargen.setToolTipText("Incluir artículos con utilidad menor a...");
        txtMargen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMargenActionPerformed(evt);
            }
        });
        txtMargen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMargenFocusGained(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(".  %  = Todos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(txtMargen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtMargen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmdImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WZPRINT.png"))); // NOI18N
        cmdImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdImprimirActionPerformed(evt);
            }
        });

        cmdCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(cmdImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCerrar)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdCerrar, cmdImprimir});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdImprimir))
                .addGap(4, 4, 4))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdCerrar, cmdImprimir});

        chkSoloOferta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkSoloOferta.setText("Sólo artículos en oferta");

        mnuArchivo.setText("Archivo");

        mnuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WZPRINT.JPG"))); // NOI18N
        mnuGuardar.setText("Imprimir");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuGuardar);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuEdicion.setText("Edición");

        mnuBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/binocular.png"))); // NOI18N
        mnuBuscar.setText("Buscar");
        mnuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarActionPerformed(evt);
            }
        });
        mnuEdicion.add(mnuBuscar);

        jMenuBar1.add(mnuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkSoloOferta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSoloOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(475, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
}//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarActionPerformed
        JTextField objeto;
        switch (objetoBusqueda){
            case ARTCODE1:
                objeto = txtArtcode1;
                break;
            case ARTCODE2:
                objeto = txtArtcode2;
                break;
            case BODEGA1:
                objeto = txtBodega1;
                break;
            case BODEGA2:
                objeto = txtBodega2;
                break;
            default:
                objeto = null;
        } // end switch

        if (objeto == null) {
            return;
        }

        // Asumo como primer buscador la tabla de artículos
        bd = new Buscador(new java.awt.Frame(), true,
                "inarticu", "artcode,artdesc", "artdesc",
                objeto,conn);
        bd.setTitle("Buscar artículos de inventario");

        if (objetoBusqueda >= BODEGA1){
            bd = new Buscador(new java.awt.Frame(), true,
                    "bodegas", "bodega,descrip", "descrip",
                    objeto,conn);
            bd.setTitle("Buscar bodegas");
        } // end if

        bd.lblBuscar.setText("Descripción:");
        bd.setVisible(true);
        bd.dispose();
}//GEN-LAST:event_mnuBuscarActionPerformed

    private void txtArtcode1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode1FocusGained
        txtArtcode1.selectAll();
        objetoBusqueda = ARTCODE1;
}//GEN-LAST:event_txtArtcode1FocusGained

    private void txtArtcode2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode2FocusGained
        txtArtcode2.selectAll();
        objetoBusqueda = ARTCODE2;
    }//GEN-LAST:event_txtArtcode2FocusGained

    private void txtArtcode1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode1FocusLost
        txtArtcode1.setText(txtArtcode1.getText().toUpperCase());
    }//GEN-LAST:event_txtArtcode1FocusLost

    private void txtArtcode2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode2FocusLost
        if (txtArtcode2.getText() == null ||
                txtArtcode2.getText().trim().equals("")){
            return;
        } // end if

        txtArtcode2.setText(txtArtcode2.getText().toUpperCase());
        String artcode1 = txtArtcode1.getText().trim();
        String artcode2 = txtArtcode2.getText().trim();
        if (artcode1.compareTo(artcode2) > 0){
            JOptionPane.showMessageDialog(null,
                    "Rango incorrecto de artículos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            txtArtcode1.requestFocusInWindow();
        } // end if
    }//GEN-LAST:event_txtArtcode2FocusLost

    private void txtBodega1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBodega1FocusGained
        txtBodega1.selectAll();
        objetoBusqueda = BODEGA1;
    }//GEN-LAST:event_txtBodega1FocusGained

    private void txtBodega1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBodega1FocusLost
        txtBodega1.setText(txtBodega1.getText().toUpperCase());
    }//GEN-LAST:event_txtBodega1FocusLost

    private void txtBodega2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBodega2FocusGained
        txtBodega2.selectAll();
        objetoBusqueda = BODEGA2;
    }//GEN-LAST:event_txtBodega2FocusGained

    private void txtBodega2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBodega2FocusLost
        if (txtBodega2.getText() == null ||
                txtBodega2.getText().trim().equals("")){
            return;
        } // end if

        txtBodega2.setText(txtBodega2.getText().toUpperCase());
        String bodega1 = txtBodega1.getText().trim();
        String bodega2 = txtBodega2.getText().trim();
        if (bodega1.compareTo(bodega2) > 0){
            JOptionPane.showMessageDialog(null,
                    "Rango incorrecto de bodegas.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            txtBodega1.requestFocusInWindow();
        } // end if
    }//GEN-LAST:event_txtBodega2FocusLost

    private void cboTipoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoRepActionPerformed
        // 0 = Máximos y mínimos
        // 1 = Costos FOB y promedio
        // 2 = Fecha último movimiento
        // 3 = Precio de lista
        // 4 = Precios y márgenes
        spnArtprec.setVisible(false);
        cboCosto.setVisible(false);
        jLabel3.setVisible(false);

        switch (cboTipoRep.getSelectedIndex()){
            case 1:
                jLabel3.setVisible(true);
                cboCosto.setVisible(true);
                break;
            case 3:
                spnArtprec.setVisible(true);
                break;
            case 4:
                spnArtprec.setVisible(true);
                break;
        } // end switch
    }//GEN-LAST:event_cboTipoRepActionPerformed

    private void txtArtcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtcode1ActionPerformed
        txtArtcode2.requestFocusInWindow();
    }//GEN-LAST:event_txtArtcode1ActionPerformed

    private void txtBodega1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBodega1ActionPerformed
        txtBodega2.requestFocusInWindow();
    }//GEN-LAST:event_txtBodega1ActionPerformed

    private void txtMargenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMargenFocusGained
        txtMargen.selectAll();
    }//GEN-LAST:event_txtMargenFocusGained

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cmdCerrarActionPerformed

    private void cmdImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdImprimirActionPerformed
        String artcode1, artcode2, bodega1, bodega2, excluir, margen,
                orden, tipoRep, precio, calculo, query, titulo;
        int aplicaOferta;
        artcode1 = txtArtcode1.getText().trim();
        artcode2 = txtArtcode2.getText().trim();
        bodega1  = txtBodega1.getText().trim();
        bodega2  = txtBodega2.getText().trim();
        aplicaOferta = (this.chkSoloOferta.isSelected()? 1 : 0); // Bosco agregado 12/03/2014
        
        titulo = "";
        
        if (bodega1.equals(bodega2)){
            try {
                titulo = 
                        UtilBD.getDBString(conn, "bodegas", "bodega = '" + bodega1 + "'" , "descrip");
            } catch (NotUniqueValueException | SQLException ex) {
                Logger.getLogger(RepExistenciasPB.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(
                        null,
                        ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                new Bitacora().writeToLog(this.getClass().getName() + "--> " + ex.getMessage());
                return;
            } // end try-catch
        } // end if

        // 1 = Excluir artículos sin existencia
        // 2 = Excluir articulos con existencia
        // 3 = no excluir
        excluir  =
                !radExcluirSE.isSelected()?
                 radExcluirCE.isSelected()? "2" : "3" : "1";

        // Establecer el margen de utilidad a procesar
        margen   = txtMargen.getText().trim();
        margen   = margen.substring(0,margen.length()-1);
        margen   = margen.trim();
        if (margen.equals(".")) {
            margen = "0";
        } // end if
        
        orden   = String.valueOf(cboOrden.getSelectedIndex());
        tipoRep = String.valueOf(cboTipoRep.getSelectedIndex());
        precio  = spnArtprec.getValue().toString();

        // 0=Costo total, 1=Costo unitario
        calculo = cboCosto.getSelectedIndex() == 0 ? "0":"1";
        
        query = "Call Rep_Existencias(" +
        "'" + artcode1 + "'" + "," +
        "'" + artcode2 + "'" + "," +
        "'" + bodega1  + "'" + "," +
        "'" + bodega2  + "'" + ","
            + excluir  + ","
            + margen   + ","
            + orden    + ","
            + calculo  + "," +
              aplicaOferta +")";
        try {
            Ut.isSQLInjection(query);
        } catch (NumberFormatException | SQLInjectionException ex) {
            Logger.getLogger(RepExistenciasPB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            new Bitacora().writeToLog(this.getClass().getName() + "--> " + ex.getMessage());
            return;
        } // end try-catch

        new Reportes(conn).existenciasPB(tipoRep, precio, query, titulo);
    }//GEN-LAST:event_cmdImprimirActionPerformed

    private void txtMargenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMargenActionPerformed
        txtMargen.transferFocus();
    }//GEN-LAST:event_txtMargenActionPerformed

    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
        cmdImprimirActionPerformed(evt);
    }//GEN-LAST:event_mnuGuardarActionPerformed


    
    /**
     * @param c
    */
    public static void main(Connection c) {
        try {
            // Bosco agregado 23/07/2011
            // Integración del segundo nivel de seguridad.
            if (!UtilBD.tienePermiso(c,"RepExistenciasPB")){
                JOptionPane.showMessageDialog(null,
                        "Usted no está autorizado para ejecutar este proceso",
                        "Error - Permisos",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } // Fin Bosco agregado 23/07/2011
            // Fin Bosco agregado 23/07/2011
        } catch (Exception ex) {
            Logger.getLogger(RepExistenciasPB.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            RepExistenciasPB run = new RepExistenciasPB(c);
            run.setVisible(true);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, 
                     ex.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboCosto;
    private javax.swing.JComboBox cboOrden;
    private javax.swing.JComboBox cboTipoRep;
    private javax.swing.JCheckBox chkSoloOferta;
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblArtcode;
    private javax.swing.JLabel lblArtcode2;
    private javax.swing.JLabel lblArtcode3;
    private javax.swing.JLabel lblArtcode4;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuBuscar;
    private javax.swing.JMenu mnuEdicion;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JRadioButton radExcluirCE;
    private javax.swing.JRadioButton radExcluirNinguno;
    private javax.swing.JRadioButton radExcluirSE;
    private javax.swing.JSpinner spnArtprec;
    private javax.swing.JFormattedTextField txtArtcode1;
    private javax.swing.JFormattedTextField txtArtcode2;
    private javax.swing.JFormattedTextField txtBodega1;
    private javax.swing.JFormattedTextField txtBodega2;
    private javax.swing.JFormattedTextField txtMargen;
    // End of variables declaration//GEN-END:variables

} // end class
