/*
 * RepPedidosyAp.java 
 *
 * Created on 04/01/2011, 09:00:00 PM
 * Modified on 21/08/2011, 02:48:00 PM Bosco Garita
 */

package interfase.reportes;

import Exceptions.EmptyDataSourceException;
import Mail.Bitacora;
import accesoDatos.UtilBD;
import interfase.otros.Buscador;
import interfase.otros.Navegador;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.utilitarios.SQLInjectionException;
import logica.utilitarios.Ut;

/**
 *
 * @author Bosco Garita
 */
@SuppressWarnings("serial")
public class RepPedidosyAp extends JFrame {

    private final ResultSet  rs;
    private Connection conn = null;
    Navegador          Nav = null;
    private Buscador   bd = null;
    private String bodega = "";
    private short objetoBusqueda = 1; // 1=txtArtcode1,2=txtArtcode2
    private final Bitacora b = new Bitacora();
    
    /** Creates new form
     * @param c
     * @param artcode
     * @throws java.sql.SQLException
     * @throws Exceptions.EmptyDataSourceException
     * @throws logica.utilitarios.SQLInjectionException */
    public RepPedidosyAp(Connection c, String artcode) 
            throws SQLException, EmptyDataSourceException, SQLInjectionException {
        initComponents();

        conn = c;

        txtArtcode1.setText("");
        txtArtcode2.setText("");

        Nav = new Navegador();
        Nav.setConexion(conn);

        // Cargar el combo de bodegas
        rs = Nav.cargarRegistro(Navegador.TODOS, "", "bodegas", "bodega");
        Ut.fillComboBox(this.cboBodega,rs,2,false);

        // Bosco agregado 21/08/2011
        setVisible(true);
        if (!artcode.isEmpty()){
            this.txtArtcode1.setText(artcode);
            this.txtArtcode2.setText(artcode);
            this.cmdImprimirActionPerformed(null);
            this.cmdCerrarActionPerformed(null);
        } // end if
    } // end constructor

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblArtcode4 = new javax.swing.JLabel();
        txtArtcode1 = new javax.swing.JFormattedTextField();
        lblArtcode2 = new javax.swing.JLabel();
        lblArtcode3 = new javax.swing.JLabel();
        txtArtcode2 = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        cmdImprimir = new javax.swing.JButton();
        cmdCerrar = new javax.swing.JButton();
        cboBodega = new javax.swing.JComboBox();
        lblArtcode5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuEdicion = new javax.swing.JMenu();
        mnuBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle de pedidos y apartados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rangos del reporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 0))); // NOI18N

        lblArtcode4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode4.setForeground(new java.awt.Color(0, 51, 255));
        lblArtcode4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode4.setText("Artículos");
        lblArtcode4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            txtArtcode1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("********************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtArtcode1.setToolTipText("Código de artículo - Blanco = todos");
        txtArtcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtcode1ActionPerformed(evt);
            }
        });
        txtArtcode1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtcode1FocusGained(evt);
            }
        });

        lblArtcode2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode2.setForeground(new java.awt.Color(255, 0, 204));
        lblArtcode2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode2.setText("Desde");
        lblArtcode2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblArtcode3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode3.setForeground(new java.awt.Color(255, 0, 204));
        lblArtcode3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode3.setText("Hasta");
        lblArtcode3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        try {
            txtArtcode2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("********************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtArtcode2.setToolTipText("Código de artículo - Blanco = todos");
        txtArtcode2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtcode2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtcode2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArtcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtcode2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtArtcode2)
                    .addComponent(lblArtcode4)
                    .addComponent(txtArtcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblArtcode4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblArtcode2)
                    .addComponent(txtArtcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblArtcode3)
                    .addComponent(txtArtcode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        cmdImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WZPRINT.png"))); // NOI18N
        cmdImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdImprimirActionPerformed(evt);
            }
        });

        cmdCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdCerrar, cmdImprimir});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdImprimir))
                .addGap(4, 4, 4))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdCerrar, cmdImprimir});

        cboBodega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas" }));
        cboBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBodegaActionPerformed(evt);
            }
        });

        lblArtcode5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArtcode5.setForeground(new java.awt.Color(0, 51, 255));
        lblArtcode5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArtcode5.setText("Bodega");
        lblArtcode5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        mnuArchivo.setText("Archivo");

        mnuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WZPRINT.JPG"))); // NOI18N
        mnuGuardar.setText("Imprimir");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuGuardar);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuEdicion.setText("Edición");

        mnuBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/binocular.png"))); // NOI18N
        mnuBuscar.setText("Buscar");
        mnuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarActionPerformed(evt);
            }
        });
        mnuEdicion.add(mnuBuscar);

        jMenuBar1.add(mnuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboBodega, 0, 297, Short.MAX_VALUE)
                            .addComponent(lblArtcode5)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArtcode5)
                .addGap(3, 3, 3)
                .addComponent(cboBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(565, 293));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
}//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarActionPerformed
        JTextField objeto;
        switch (objetoBusqueda){
            case 1:
                objeto = txtArtcode1;
                break;
            case 2:
                objeto = txtArtcode2;
                break;            
            default:
                objeto = null;
        } // end switch

        if (objeto == null){
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar alguno de los " +
                    "campos de artículo " +
                    "\nantes de usar la opción de búsqueda.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } // end if

        bd = new Buscador(new java.awt.Frame(), true,
                "inarticu", "artcode,artdesc", "artdesc",
                objeto,conn);
        bd.setTitle("Buscar artículos");
        
        bd.lblBuscar.setText("Artículo:");
        bd.setVisible(true);
        bd.dispose();
}//GEN-LAST:event_mnuBuscarActionPerformed

    private void txtArtcode1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode1FocusGained
        txtArtcode1.selectAll();
        objetoBusqueda = 1;
    }//GEN-LAST:event_txtArtcode1FocusGained

    private void txtArtcode2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode2FocusGained
        txtArtcode2.selectAll();
        objetoBusqueda = 2;
    }//GEN-LAST:event_txtArtcode2FocusGained

    private void txtArtcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtcode1ActionPerformed
        txtArtcode2.requestFocusInWindow();
    }//GEN-LAST:event_txtArtcode1ActionPerformed

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cmdCerrarActionPerformed

    private void cmdImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdImprimirActionPerformed
        String  artcode1, artcode2,
                query,filtro,formJasper;

        artcode1 = txtArtcode1.getText().trim();
        artcode2 = txtArtcode2.getText().trim();

        formJasper = "RepPedidosyAp.jasper";

        filtro = "Rangos del reporte: ";

        if ((artcode1.isEmpty() && artcode2.isEmpty()) ||
                (artcode1.trim().equals("") && artcode2.trim().equals(""))){
            filtro += "Todos los artículos, ";
        }else{
            filtro += "Artículos de " + artcode1 + " a " +
                    artcode2 + ", ";
        } // end if

        if(this.bodega.isEmpty()){
            filtro += "Todas las bodegas.";
        }else{
            filtro += "Bodega " + this.bodega;
        } // end if

       
        query = "Call Rep_PedidosyAp(" +
                "'" + artcode1 + "'" + "," +
                "'" + artcode2 + "'" + "," +
                "'" + bodega   + "'" + ")";
         
        new Reportes(conn).generico(
                query,
                "",     // where
                "",     // Order By
                filtro,
                formJasper,
                "Detalle de pedidos y apartados");
    }//GEN-LAST:event_cmdImprimirActionPerformed

    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
        cmdImprimirActionPerformed(evt);
    }//GEN-LAST:event_mnuGuardarActionPerformed

    private void txtArtcode2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcode2FocusLost
        if (txtArtcode2.getText() == null ||
                txtArtcode2.getText().trim().equals("")){
            return;
        } // end if

        String artcode1 = txtArtcode1.getText().trim();
        String artcode2 = txtArtcode2.getText().trim();
        if (artcode1.compareTo(artcode2) > 0){
            JOptionPane.showMessageDialog(null,
                    "Rango incorrecto.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            txtArtcode1.requestFocusInWindow();
        } // end if
}//GEN-LAST:event_txtArtcode2FocusLost

    private void cboBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBodegaActionPerformed
        String descrip = cboBodega.getSelectedItem().toString().trim();
        this.bodega = "";
        
        try {
            if (descrip.equalsIgnoreCase("Todas") ||
                    !Ut.seek(rs, descrip, "Descrip")){
                return;
            } // end if
            this.bodega = rs.getString("bodega");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                    null,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            b.writeToLog(this.getClass().getName() + "--> " + ex.getMessage());
        } // end catch
        //JOptionPane.showMessageDialog(null, this.bodega);
    }//GEN-LAST:event_cboBodegaActionPerformed


    /**
     * @param c
     * @param artcode
    */
    public static void main(Connection c, String artcode) {
        try {
            // Bosco agregado 23/07/2011
            // Integración del segundo nivel de seguridad.
            if (!UtilBD.tienePermiso(c,"RepPedidosyAp")){
                JOptionPane.showMessageDialog(null,
                        "Usted no está autorizado para ejecutar este proceso",
                        "Error - Permisos",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } // Fin Bosco agregado 23/07/2011
            // Fin Bosco agregado 23/07/2011
        } catch (Exception ex) {
            Logger.getLogger(RepPedidosyAp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            RepPedidosyAp run = new RepPedidosyAp(c,artcode);
            //run.setVisible(true);
        } catch (SQLException | EmptyDataSourceException | SQLInjectionException ex) {
             JOptionPane.showMessageDialog(
                     null, ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboBodega;
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdImprimir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblArtcode2;
    private javax.swing.JLabel lblArtcode3;
    private javax.swing.JLabel lblArtcode4;
    private javax.swing.JLabel lblArtcode5;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuBuscar;
    private javax.swing.JMenu mnuEdicion;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JFormattedTextField txtArtcode1;
    private javax.swing.JFormattedTextField txtArtcode2;
    // End of variables declaration//GEN-END:variables

} // end class
