/*
 * ConsolaIntegridad.java
 *
 * Created on 09/10/2011, 04:49:44 PM
 */

package interfase.otros;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Bosco
 */
public class ConsolaIntegridad extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    /** Creates new form ConsolaIntegridad */
    public ConsolaIntegridad() {
        initComponents();
        
        //this.L1.setVisible(false);
        this.L2.setVisible(false);
        this.L3.setVisible(false);
        this.L4.setVisible(false);
        this.L5.setVisible(false);
        this.L6.setVisible(false);
        this.L7.setVisible(false);
        this.L8.setVisible(false);
        this.L9.setVisible(false);
        this.L10.setVisible(false);
        this.L11.setVisible(false);
        this.L12.setVisible(false);
        this.L13.setVisible(false);
        this.L14.setVisible(false);
        this.L15.setVisible(false);
        this.L16.setVisible(false);

        this.L1.setText("");
        this.L2.setText("");
        this.L3.setText("");
        this.L4.setText("");
        this.L5.setText("");
        this.L6.setText("");
        this.L7.setText("");
        this.L8.setText("");
        this.L9.setText("");
        this.L10.setText("");
        this.L11.setText("");
        this.L12.setText("");
        this.L13.setText("");
        this.L14.setText("");
        this.L15.setText("");
        this.L16.setText("");

        //mostrarMensaje();
        setVisible(true);
    } // end constructor


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        L11 = new javax.swing.JLabel();
        L12 = new javax.swing.JLabel();
        L13 = new javax.swing.JLabel();
        L14 = new javax.swing.JLabel();
        L15 = new javax.swing.JLabel();
        L16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        L1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L1.setText("jLabel1");

        L2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L2.setText("jLabel1");

        L3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L3.setText("jLabel1");

        L4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L4.setText("jLabel1");

        L5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L5.setText("jLabel1");

        L6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L6.setText("jLabel1");

        L7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L7.setText("jLabel1");

        L8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L8.setText("jLabel1");

        L9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L9.setText("jLabel1");

        L10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L10.setText("jLabel1");

        L11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L11.setText("jLabel1");

        L12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L12.setText("jLabel1");

        L13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L13.setText("jLabel1");

        L14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L14.setText("jLabel1");

        L15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L15.setText("jLabel1");

        L16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        L16.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L7, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L11, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L12, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L13, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L10, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L14, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L15, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L16, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L9)
                .addGap(5, 5, 5)
                .addComponent(L10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L16)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConsolaIntegridad().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L11;
    private javax.swing.JLabel L12;
    private javax.swing.JLabel L13;
    private javax.swing.JLabel L14;
    private javax.swing.JLabel L15;
    private javax.swing.JLabel L16;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    // End of variables declaration//GEN-END:variables

    public void agregarTexto(String texto, int etiqueta, Color c){
        switch(etiqueta){
            case 1:
                L1.setText(L1.getText() + texto);
                L1.setForeground(c);
                L1.setVisible(true);
                break;
            case 2:
                L2.setText(L2.getText() + texto);
                L2.setForeground(c);
                L2.setVisible(true);
                break;
            case 3:
                L3.setText(L3.getText() + texto);
                L3.setForeground(c);
                L3.setVisible(true);
                break;
            case 4:
                L4.setText(L4.getText() + texto);
                L4.setForeground(c);
                L4.setVisible(true);
                break;
            case 5:
                L5.setText(L5.getText() + texto);
                L5.setForeground(c);
                L5.setVisible(true);
                break;
            case 6:
                L6.setText(L6.getText() + texto);
                L6.setForeground(c);
                L6.setVisible(true);
                break;
            case 7:
                L7.setText(L7.getText() + texto);
                L7.setForeground(c);
                L7.setVisible(true);
                break;
            case 8:
                L8.setText(L8.getText() + texto);
                L8.setForeground(c);
                L8.setVisible(true);
                break;
            case 9:
                L9.setText(L9.getText() + texto);
                L9.setForeground(c);
                L9.setVisible(true);
                break;
            case 10:
                L10.setText(L10.getText() + texto);
                L10.setForeground(c);
                L10.setVisible(true);
                break;
            case 11:
                L11.setText(L11.getText() + texto);
                L11.setForeground(c);
                L11.setVisible(true);
                break;
            case 12:
                L12.setText(L12.getText() + texto);
                L12.setForeground(c);
                L12.setVisible(true);
                break;
            case 13:
                L13.setText(L13.getText() + texto);
                L13.setForeground(c);
                L13.setVisible(true);
                break;
            case 14:
                L14.setText(L14.getText() + texto);
                L14.setForeground(c);
                L14.setVisible(true);
                break;
            case 15:
                L15.setText(L15.getText() + texto);
                L15.setForeground(c);
                L15.setVisible(true);
                break;
            case 16:
                L16.setText(L16.getText() + texto);
                L16.setForeground(c);
                L16.setVisible(true);
                break;

        } // end switch
    } // end agregarTexto

    private void mostrarMensaje(){
        JOptionPane.showMessageDialog(null,
                    "Este proceso puede tardar varios minutos.\n\n"
                    + "Presione ENTER para continuar...",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);

    } // end mostrarMensaje
}
