/*
 * FacturacionNoEnInv.java
 *
 * Created on 19/02/2011, 08:33:04 PM
 * 
 * Normalmente es llamado por el menú principal en el proceso de
 * revisión de la integridad de la base de datos.
 */

package interfase.otros;

import java.awt.Dialog;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bosco
 */
@SuppressWarnings("serial")
public class Incongruecias extends javax.swing.JFrame {

    /** Creates new form FacturacionNoEnInv
     * @param rs
     * @param titulo
     * @throws java.sql.SQLException */
    public Incongruecias(ResultSet rs, String titulo) throws SQLException {
        initComponents();
        if (rs == null || !rs.first()){
            return;
        } // end if

        this.lblTitulo.setText(titulo);
        this.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        // Establecer la filas de la tabla y cargar los datos
        rs.last();
        int dataRows = rs.getRow() > 0 ? rs.getRow() : 12;

        DefaultTableModel dtm = (DefaultTableModel) tblFacturas.getModel();
        dtm.setRowCount(dataRows);
        tblFacturas.setModel(dtm);

        // Cargo los datos desde el ResultSet
        int fila = 0;
        rs.beforeFirst();
        while (rs.next()){
            tblFacturas.setValueAt(rs.getObject(2), fila, 0); // Documento
            tblFacturas.setValueAt(rs.getObject(6), fila, 1); // Tipo
            tblFacturas.setValueAt(rs.getObject(4), fila, 2); // Monto
            tblFacturas.setValueAt(rs.getObject(3), fila, 3); // Fecha
            tblFacturas.setValueAt(rs.getObject(5), fila, 4); // Plazo
            fila++;
        } // end while
        rs.close();
        //JOptionPane.showMessageDialog(null, "Mostrar datgos");
    } // end constructor

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        cmdCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Integridad de datos");
        setAlwaysOnTop(true);

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Documento", "Tipo", "Monto", "Fecha", "Plazo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFacturas);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setForeground(java.awt.Color.red);
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Facturas y/o notas de crédito que no se encuentran en inventarios");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmdCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(cmdCerrar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(cmdCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        setSize(new java.awt.Dimension(620, 325));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        dispose();
}//GEN-LAST:event_cmdCerrarActionPerformed

    /**
     * @param rs
     * @param titulo
    */
    public static void main(final ResultSet rs, final String titulo) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Incongruecias(rs, titulo).setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(
                            null,
                            ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                } // end catch
            } // end run
        });
    } // end main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFacturas;
    // End of variables declaration//GEN-END:variables

} // end Incongruecias
