/*
 * RecodificacionArticulos.java
 *
 * Created on 17/04/2011, 02:42:00 PM
 */

package interfase.transacciones;

import Exceptions.NotUniqueValueException;
import Mail.Bitacora;
import accesoDatos.UtilBD;
import interfase.otros.Buscador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bosco Garita
 */
@SuppressWarnings("serial")
public class RecodificacionArticulos extends JFrame {

    private Connection conn = null;
    private final Bitacora b = new Bitacora();
    
    /** Creates new form */
    public RecodificacionArticulos(Connection c) throws SQLException {
        initComponents();
        // Defino el escuchador con una clase anónima para controlar la
        // salida de esta pantalla.  Esto funciona simpre que se haya
        // establecido el siguiente parámetro:
        // setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE)
        // Esta pantalla lo hace en initComponents().
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                cmdCerrarActionPerformed(null);
            } // end windowClosing
        } // end class
        ); // end Listener

        conn = c;

    } // end constructor

    public void setConexion(Connection c){ conn = c; }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtArtcodeNuevo = new javax.swing.JTextField();
        txtArtcodeOriginal = new javax.swing.JTextField();
        txtArtdesc = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuEdicion = new javax.swing.JMenu();
        mnuBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Recodificar artículos");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 255));
        jLabel12.setText("Código original");

        cmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WZSAVE.png"))); // NOI18N
        cmdGuardar.setToolTipText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        cmdCerrar.setToolTipText("Salir");
        cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmdCerrar, cmdGuardar});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmdCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cmdGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmdCerrar, cmdGuardar});

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Nuevo código");

        txtArtcodeNuevo.setToolTipText("Buscar");
        txtArtcodeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtcodeNuevoActionPerformed(evt);
            }
        });
        txtArtcodeNuevo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtcodeNuevoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtcodeNuevoFocusLost(evt);
            }
        });

        txtArtcodeOriginal.setToolTipText("Buscar");
        txtArtcodeOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtcodeOriginalActionPerformed(evt);
            }
        });
        txtArtcodeOriginal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtArtcodeOriginalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtcodeOriginalFocusLost(evt);
            }
        });

        txtArtdesc.setEditable(false);
        txtArtdesc.setForeground(new java.awt.Color(0, 0, 255));
        txtArtdesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArtdesc.setFocusable(false);

        mnuArchivo.setText("Archivo");

        mnuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WZSAVE.JPG"))); // NOI18N
        mnuGuardar.setText("Guardar");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuGuardar);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/control-power.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar1.add(mnuArchivo);

        mnuEdicion.setText("Edición");

        mnuBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/binocular.png"))); // NOI18N
        mnuBuscar.setText("Buscar");
        mnuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarActionPerformed(evt);
            }
        });
        mnuEdicion.add(mnuBuscar);

        jMenuBar1.add(mnuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArtdesc, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArtcodeOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtArtcodeNuevo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtArtcodeOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArtcodeNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        setSize(new java.awt.Dimension(379, 235));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
}//GEN-LAST:event_mnuSalirActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        String artcodeOriginal, artcodeNuevo;
        artcodeOriginal = txtArtcodeOriginal.getText().trim();
        artcodeNuevo    = txtArtcodeNuevo.getText().trim();

        String errorMessage = "";
        JTextField f = null;

        // Validaciones.
        if (txtArtdesc.getText().trim().isEmpty()){
            errorMessage = "-Artículo no existe.";
            f = txtArtcodeOriginal;
        } // end if

        if (artcodeNuevo.isEmpty()){
            errorMessage += "\n-Artículo no puede quedar en blanco.";
            if (f == null){
                f = txtArtcodeNuevo;
            } // end if
        } // end if

        if (artcodeOriginal.equals(artcodeNuevo)){
            errorMessage += "\n-El código original y el nuevo son iguales.";
            if (f == null){
                f = txtArtcodeNuevo;
            } // end if
        } // end if

        if (!errorMessage.isEmpty()){
            JOptionPane.showMessageDialog(
                    null,
                    errorMessage,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            if (f != null) {
                f.requestFocusInWindow();
            } // end if
            
            return;
        } // end if

        // El SP valida que el nuevo código no exista.
        
        String sqlCall = "Call RecodificarArticulo(?,?)";

        try{
            // No se usa transacción porque el mismo SP lo hace.
            CallableStatement cs = conn.prepareCall(sqlCall);

            // Registrar los parámetros de entrada
            cs.setString(1, artcodeOriginal);
            cs.setString(2, artcodeNuevo);
            try (ResultSet rsx = cs.executeQuery()) {
                if (rsx == null) {
                    errorMessage = "El proceso no se pudo ejecutar";
                }else{
                    rsx.first();
                    if (rsx.getBoolean(1)) {
                        errorMessage = rsx.getString(2);
                    } // end if
                } // end if-else

                if (!errorMessage.isEmpty()){
                    JOptionPane.showMessageDialog(
                         null,
                         errorMessage,
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            JOptionPane.showMessageDialog(
                 null,
                 "Artículo recodificado satisfactoriamente.",
                "Mensaje",
                JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                     null,
                     ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            b.writeToLog(this.getClass().getName() + "--> " + ex.getMessage(), Bitacora.ERROR);
        }
}//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
        dispose();
}//GEN-LAST:event_cmdCerrarActionPerformed

    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
        cmdGuardarActionPerformed(evt);
}//GEN-LAST:event_mnuGuardarActionPerformed
    /**
     * Cuando el usuario decide hacer un conteo selectivo el sistema
     * tomará todas las cantidades en existencia y las pasará al campo
     * cantidad que sería lo que él tendría que digitar.  Esto se hace
     * con el fin de que el usuaria se dedique a cambiar los datos que
     * se contaron nada más.
     * Con lo que hay que tener cuidado es que si el usuario decide usar
     * la opción de Conteo Selectivo el sistema ignorará cualquier dato
     * que estén modificando otros usuarios en esta tabla de conteo y
     * volverá a cargar todo para uso del usuario que utilizó esta opción.
     * @param evt
     */
    private void txtArtcodeOriginalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcodeOriginalFocusGained
        txtArtcodeOriginal.selectAll();
    }//GEN-LAST:event_txtArtcodeOriginalFocusGained

    private void mnuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarActionPerformed
        Buscador bd;

        bd = new Buscador(new java.awt.Frame(), true,
            "inarticu","artcode,artdesc","artdesc",txtArtcodeOriginal,conn);
        bd.setTitle("Buscar artículos de inventario");
        bd.lblBuscar.setText("Descripción:");
        bd.setVisible(true);
        txtArtcodeOriginalActionPerformed(null);
        bd.dispose();
}//GEN-LAST:event_mnuBuscarActionPerformed

    private void txtArtcodeOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtcodeOriginalActionPerformed
        txtArtcodeOriginal.setText(txtArtcodeOriginal.getText().toUpperCase());
        String artcode = txtArtcodeOriginal.getText().trim();
        String condicion = "artcode = " + "'" + artcode + "'";
        try {
            txtArtdesc.setText(
                    UtilBD.getDBString(conn,"inarticu",condicion,"artdesc"));
        } catch (NotUniqueValueException | SQLException ex) {
            Logger.getLogger(RecodificacionArticulos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(
                    null,
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            b.writeToLog(this.getClass().getName() + "--> " + ex.getMessage(), Bitacora.ERROR);
            return;
        }
        txtArtcodeOriginal.transferFocus();
    }//GEN-LAST:event_txtArtcodeOriginalActionPerformed

    private void txtArtcodeNuevoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcodeNuevoFocusGained
        txtArtcodeNuevo.selectAll();
    }//GEN-LAST:event_txtArtcodeNuevoFocusGained

    private void txtArtcodeNuevoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcodeNuevoFocusLost
        txtArtcodeNuevo.setText(txtArtcodeNuevo.getText().toUpperCase());
    }//GEN-LAST:event_txtArtcodeNuevoFocusLost

    private void txtArtcodeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtcodeNuevoActionPerformed
        txtArtcodeNuevo.transferFocus();
    }//GEN-LAST:event_txtArtcodeNuevoActionPerformed

    private void txtArtcodeOriginalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtcodeOriginalFocusLost
        txtArtcodeOriginal.setText(txtArtcodeOriginal.getText().toUpperCase());
    }//GEN-LAST:event_txtArtcodeOriginalFocusLost


    /**
     * @param c
    */
    public static void main(Connection c) {
        try {
            // Bosco agregado 18/07/2011
            // Integración del segundo nivel de seguridad.
            if (!UtilBD.tienePermiso(c,"RecodificacionArticulos")){
                JOptionPane.showMessageDialog(null,
                        "Usted no está autorizado para ejecutar este proceso",
                        "Error - Permisos",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } // Fin Bosco agregado 18/07/2011
            // Fin Bosco agregado 18/07/2011
        } catch (Exception ex) {
            Logger.getLogger(RecodificacionArticulos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, 
                    ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        //JFrame.setDefaultLookAndFeelDecorated(true);
        try {
            RecodificacionArticulos run = new RecodificacionArticulos(c);
            run.setVisible(true);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,
                     ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCerrar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuBuscar;
    private javax.swing.JMenu mnuEdicion;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextField txtArtcodeNuevo;
    private javax.swing.JTextField txtArtcodeOriginal;
    private javax.swing.JTextField txtArtdesc;
    // End of variables declaration//GEN-END:variables
} // end class
